format = """$python$directory$character"""

right_format = """$memory_usage"""

add_newline = false
continuation_prompt = '▶▶ '

[memory_usage]
disabled = false
threshold = 0
symbol = "󰍛 "

[python]
style = "#3776AB"
format = "$virualenv"
